packages:
  - "artifacts/api-server"
  - "artifacts/academic-workspace"
  - "lib/*"
  - "scripts"
allowBuilds:
  '@playwright/browser-chromium': set this to true or false
  '@playwright/browser-firefox': set this to true or false
  '@playwright/browser-webkit': set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
