import type { CitationFormat } from "./citation.js";
import { logger } from "./logger.js";

/**
 * Citation Rendering — Phase 2 of DECISION 014.
 *
 * Takes raw document text + citation rows, returns rendered HTML with
 * citation markers injected at the right (paragraphIndex, offsetInParagraph)
 * positions, plus a formatted bibliography.
 *
 * This is a SEPARATE module from `citation.ts` to keep the rendering
 * concerns isolated from the CSL/bibliography concerns. The `citation.ts`
 * file focuses on marker formatting + bibliography generation; this file
 * focuses on HTML rendering + paragraph splitting.
 */

export interface CitationForRender {
  id: number;
  referenceId: number;
  paragraphIndex: number;
  offsetInParagraph: number;
  formatMarker: string;
  placementReason: string | null;
  reference: {
    title: string | null;
    authors: string | null;
    year: number | string | null;
    journal: string | null;
    doi: string | null;
    url: string | null;
  };
}

export interface RenderedParagraph {
  index: number;
  html: string;
}

const NUMBERED_FORMATS: ReadonlySet<CitationFormat> = new Set([
  "IEEE",
  "Vancouver",
  "Chicago",
]);

/**
 * Escape HTML special characters to prevent XSS when rendering AI-generated
 * document content via dangerouslySetInnerHTML. AI output is treated as
 * untrusted user input.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Split raw AI document content into paragraphs using the same regex the
 * auto-cite endpoint uses (`/artifacts/api-server/src/routes/references.ts:1053`).
 *
 * Handles `\n\n`, `\n \n`, and triple+ newlines as paragraph separators.
 * Filters empty paragraphs.
 */
export function splitParagraphs(content: string): string[] {
  return content
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
}

/**
 * For numbered citation formats (IEEE, Vancouver, Chicago), the marker number
 * should reflect ORDER OF APPEARANCE in the document, not `reference.id`.
 *
 * Returns a map from referenceId → sequential number (1, 2, 3, ...).
 * References cited multiple times get the same number on all occurrences.
 *
 * For non-numbered formats (APA, APA7, MLA, Harvard), returns an empty map
 * — the original `formatMarker` field stored at citation-creation time is
 * already correct.
 */
export function computeSequentialNumbers(
  citations: CitationForRender[],
): Map<number, number> {
  if (citations.length === 0) return new Map();

  // Sort by document position: paragraphIndex ASC, then offsetInParagraph ASC
  const sorted = [...citations].sort((a, b) => {
    if (a.paragraphIndex !== b.paragraphIndex) {
      return a.paragraphIndex - b.paragraphIndex;
    }
    return a.offsetInParagraph - b.offsetInParagraph;
  });

  const refToNumber = new Map<number, number>();
  let counter = 0;
  for (const c of sorted) {
    if (!refToNumber.has(c.referenceId)) {
      counter += 1;
      refToNumber.set(c.referenceId, counter);
    }
  }
  return refToNumber;
}

/**
 * Get the marker text to render for a given citation. For numbered formats,
 * uses the sequential number from the map. For author-date formats, uses
 * the pre-rendered `formatMarker` from the DB row (which was generated by
 * `formatCitationMarker` at citation creation or PATCH /citation-format time).
 */
export function getMarkerForCitation(
  citation: CitationForRender,
  format: CitationFormat,
  sequentialNumbers: Map<number, number>,
): string {
  if (NUMBERED_FORMATS.has(format) && sequentialNumbers.has(citation.referenceId)) {
    return `[${sequentialNumbers.get(citation.referenceId)}]`;
  }
  return citation.formatMarker;
}

/**
 * Build the tooltip text shown when user hovers a citation marker.
 * Concise: title + author + year + optional reason.
 */
function buildTooltip(
  citation: CitationForRender,
  marker: string,
  format: CitationFormat,
): string {
  const parts: string[] = [];
  const ref = citation.reference;
  if (ref.authors) parts.push(ref.authors);
  if (ref.year) parts.push(`(${ref.year})`);
  if (ref.title) parts.push(`— ${ref.title}`);
  if (citation.placementReason) {
    parts.push(`\nAlasan: ${citation.placementReason}`);
  }
  parts.push(`\n[${format}] ${marker} — klik untuk edit`);
  return parts.join(" ").trim();
}

/**
 * Render a single citation marker as an HTML `<sup>` tag with hover tooltip
 * and a data-citation-id attribute so the frontend can attach click handlers.
 *
 * Output shape: `<sup class="cite-marker" data-citation-id="123" title="...">[1]</sup>`
 */
export function renderMarkerHtml(
  citation: CitationForRender,
  marker: string,
  format: CitationFormat,
): string {
  const tooltip = buildTooltip(citation, marker, format);
  const tooltipEscaped = escapeHtml(tooltip).replace(/\n/g, "&#10;");
  return `<sup class="cite-marker" data-citation-id="${citation.id}" title="${tooltipEscaped}">${escapeHtml(marker)}</sup>`;
}

/**
 * Render plain markdown-ish text (headings + lists + paragraphs) to HTML.
 * Lightweight parser — no need for `marked` or `markdown-it` dependency.
 *
 * Supported:
 * - `# Heading` → `<h1>`, `##` → `<h2>`, etc up to `######`
 * - `- item` or `* item` → `<ul><li>item</li></ul>`
 * - Plain text → `<p>text</p>` (with citation markers passed in)
 */
export function renderMarkdownLight(text: string): string {
  const lines = text.split("\n");
  const blocks: string[] = [];
  let currentList: string[] = [];
  let paragraphBuffer: string[] = [];

  const flushParagraph = () => {
    if (paragraphBuffer.length > 0) {
      blocks.push(`<p>${paragraphBuffer.join("<br/>")}</p>`);
      paragraphBuffer = [];
    }
  };

  const flushList = () => {
    if (currentList.length > 0) {
      blocks.push(`<ul>${currentList.map((i) => `<li>${i}</li>`).join("")}</ul>`);
      currentList = [];
    }
  };

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();
    if (!line.trim()) {
      flushParagraph();
      flushList();
      continue;
    }
    const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
    if (headingMatch) {
      flushParagraph();
      flushList();
      const level = headingMatch[1].length;
      blocks.push(`<h${level}>${headingMatch[2]}</h${level}>`);
      continue;
    }
    const listMatch = line.match(/^[-*]\s+(.+)$/);
    if (listMatch) {
      flushParagraph();
      currentList.push(listMatch[1]);
      continue;
    }
    // Plain text line
    flushList();
    paragraphBuffer.push(line);
  }
  flushParagraph();
  flushList();

  return blocks.join("\n");
}

/**
 * Render a single paragraph's text + citation markers into HTML.
 *
 * Algorithm:
 * 1. Get citations for this paragraph, sort by offsetInParagraph DESCENDING
 *    (so inserting at offset N doesn't shift offsets N+1, N+2, ...)
 * 2. For each citation at offset O, insert marker HTML at position O
 * 3. Render the resulting text as markdown-light HTML
 *
 * Citations whose `offsetInParagraph` is past end of paragraph are clamped
 * to the end (handles edge case where paragraph was edited but citation
 * wasn't repositioned).
 */
export function renderParagraph(
  paragraphText: string,
  paragraphIndex: number,
  citationsForParagraph: CitationForRender[],
  format: CitationFormat,
  sequentialNumbers: Map<number, number>,
): string {
  // Sort descending so we insert from end to start (offsets stay stable)
  const sorted = [...citationsForParagraph].sort(
    (a, b) => b.offsetInParagraph - a.offsetInParagraph,
  );

  // Clamp offsets to valid range
  const maxOffset = paragraphText.length;
  const text = paragraphText;

  // Build HTML incrementally
  const segments: string[] = [];
  let cursor = text.length;

  for (const c of sorted) {
    const safeOffset = Math.min(Math.max(c.offsetInParagraph, 0), maxOffset);
    const marker = getMarkerForCitation(c, format, sequentialNumbers);
    const markerHtml = renderMarkerHtml(c, marker, format);

    // Text from safeOffset to cursor (the part AFTER the marker)
    const afterText = escapeHtml(text.slice(safeOffset, cursor));
    segments.push(afterText, markerHtml);
    cursor = safeOffset;
  }
  // Initial text from 0 to cursor (BEFORE the first marker)
  segments.push(escapeHtml(text.slice(0, cursor)));

  // Reverse segments to get correct order, join
  const htmlWithCitations = segments.reverse().join("");

  // Now apply markdown-light rendering. Since we've already escaped HTML
  // for safety, we need to render markdown tags BEFORE escaping, OR use
  // a render-then-merge approach.
  //
  // Approach: detect markdown structure (headings/lists) in the ORIGINAL
  // paragraph text, then map citation offsets to the rendered output.
  // For Phase 2 simplicity: render markdown on text WITHOUT citations first,
  // then re-insert citation markers using their original positions.
  //
  // But the citation positions point to the ORIGINAL text, not the rendered
  // HTML. So we render markdown-light on a "citation-tagged" version where
  // citations are represented as `<x-cite id="N" />` placeholders, then
  // convert placeholders to real HTML.
  //
  // For Phase 2 we use the simpler approach: assume most paragraphs are
  // plain prose (not headings/lists) and render directly. If a paragraph
  // starts with `#` or `-`, render as markdown and append citations at end
  // (less accurate for offset positioning, but covers 95% of cases).

  const isStructured = /^(#{1,6}\s|[-*]\s)/m.test(text);
  if (isStructured) {
    logger.debug(
      { paragraphIndex },
      "Paragraph has markdown structure — using simplified render",
    );
    // For structured paragraphs, render markdown first then append citations
    // at the end of the block. Offsets are best-effort.
    const mdHtml = renderMarkdownLight(text);
    // Append all citation markers at end of last block
    const markers = sorted
      .map((c) => {
        const marker = getMarkerForCitation(c, format, sequentialNumbers);
        return renderMarkerHtml(c, marker, format);
      })
      .join(" ");
    return mdHtml + (markers ? " " + markers : "");
  }

  // Plain paragraph: use the citation-injected HTML and wrap in <p>
  return `<p>${htmlWithCitations}</p>`;
}

/**
 * Render the full document: paragraphs + bibliography + metadata.
 */
export function renderDocument(params: {
  content: string;
  citations: CitationForRender[];
  format: CitationFormat;
  formatBibliographyFn: (refs: Array<{
    title: string | null;
    authors: string | null;
    year: number | string | null;
    journal: string | null;
    volume: number | string | null;
    issue: number | string | null;
    doi: string | null;
    url: string | null;
  }>) => string;
}): {
  paragraphs: RenderedParagraph[];
  bibliography: string;
  citationCount: number;
} {
  const { content, citations, format, formatBibliographyFn } = params;
  const paragraphs = splitParagraphs(content);
  const sequentialNumbers = computeSequentialNumbers(citations);

  const rendered: RenderedParagraph[] = paragraphs.map((text, index) => {
    const citationsForParagraph = citations.filter(
      (c) => c.paragraphIndex === index,
    );
    return {
      index,
      html: renderParagraph(
        text,
        index,
        citationsForParagraph,
        format,
        sequentialNumbers,
      ),
    };
  });

  // Bibliography: only refs that have at least one citation
  const citedRefIds = new Set(citations.map((c) => c.referenceId));
  const citedRefs = citations
    .filter((c) => citedRefIds.has(c.referenceId))
    .map((c) => c.reference)
    // Deduplicate by id (we used Set above but still need to dedupe the array)
    .filter(
      (ref, idx, arr) =>
        arr.findIndex((r) => r === ref || (ref as any).id === (r as any).id) === idx,
    )
    .map((r) => ({
      title: r.title,
      authors: r.authors,
      year: r.year,
      journal: r.journal,
      volume: null,
      issue: null,
      doi: r.doi,
      url: r.url,
    }));

  const bibliography = formatBibliographyFn(citedRefs);

  return {
    paragraphs: rendered,
    bibliography,
    citationCount: citations.length,
  };
}

/**
 * Re-render citation markers for a numbered format using sequential numbers.
 * Used by PATCH /citation-format to overwrite the formatMarker field for
 * IEEE/Vancouver/Chicago citations.
 *
 * Returns map of citationId → new formatMarker string.
 */
export function renumberMarkers(
  citations: CitationForRender[],
  format: CitationFormat,
): Map<number, string> {
  const sequentialNumbers = computeSequentialNumbers(citations);
  const updates = new Map<number, string>();

  for (const c of citations) {
    const newMarker = getMarkerForCitation(c, format, sequentialNumbers);
    if (newMarker !== c.formatMarker) {
      updates.set(c.id, newMarker);
    }
  }

  return updates;
}
